'use client';

import { useState } from 'react';
import { SearchResult } from '@/types';
import { 
  Download, 
  FileText, 
  Share2, 
  Copy, 
  Mail,
  Link,
  X
} from 'lucide-react';

interface SearchResultsExportProps {
  results: SearchResult[];
  query: string;
  onClose: () => void;
  isOpen: boolean;
}

export default function SearchResultsExport({ 
  results, 
  query, 
  onClose, 
  isOpen 
}: SearchResultsExportProps) {
  const [exportFormat, setExportFormat] = useState<'csv' | 'json' | 'txt'>('csv');
  const [includeMetadata, setIncludeMetadata] = useState(true);
  const [maxResults, setMaxResults] = useState(results.length);
  const [shareMethod, setShareMethod] = useState<'link' | 'email' | 'copy'>('copy');

  if (!isOpen) return null;

  const exportToCsv = () => {
    const headers = ['Title', 'Type', 'Content', 'Relevance Score'];
    if (includeMetadata) {
      headers.push('Entity Type', 'File Name', 'Word Count');
    }

    const csvContent = [
      headers.join(','),
      ...results.slice(0, maxResults).map(result => {
        const row = [
          `"${result.title.replace(/"/g, '""')}"`,
          result.type,
          `"${result.content.replace(/"/g, '""').substring(0, 500)}..."`,
          result.relevance_score.toFixed(3)
        ];
        
        if (includeMetadata) {
          row.push(
            result.metadata?.entity_type || '',
            result.metadata?.file_name || '',
            result.metadata?.word_count?.toString() || ''
          );
        }
        
        return row.join(',');
      })
    ].join('\n');

    downloadFile(csvContent, `search-results-${Date.now()}.csv`, 'text/csv');
  };

  const exportToJson = () => {
    const exportData = {
      query,
      timestamp: new Date().toISOString(),
      totalResults: results.length,
      exportedResults: maxResults,
      results: results.slice(0, maxResults).map(result => ({
        id: result.id,
        title: result.title,
        type: result.type,
        content: result.content,
        relevanceScore: result.relevance_score,
        highlights: result.highlights,
        ...(includeMetadata && { metadata: result.metadata })
      }))
    };

    const jsonContent = JSON.stringify(exportData, null, 2);
    downloadFile(jsonContent, `search-results-${Date.now()}.json`, 'application/json');
  };

  const exportToText = () => {
    const textContent = [
      `Search Results for: "${query}"`,
      `Generated: ${new Date().toLocaleString()}`,
      `Total Results: ${results.length}`,
      `Exported: ${maxResults}`,
      '',
      '=' .repeat(50),
      '',
      ...results.slice(0, maxResults).map((result, index) => [
        `${index + 1}. ${result.title}`,
        `   Type: ${result.type}`,
        `   Relevance: ${Math.round(result.relevance_score * 100)}%`,
        `   Content: ${result.content.substring(0, 300)}...`,
        ...(includeMetadata && result.metadata ? [
          `   File: ${result.metadata.file_name || 'Unknown'}`,
          `   Entity Type: ${result.metadata.entity_type || 'N/A'}`
        ] : []),
        ''
      ]).flat()
    ].join('\n');

    downloadFile(textContent, `search-results-${Date.now()}.txt`, 'text/plain');
  };

  const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  const handleExport = () => {
    switch (exportFormat) {
      case 'csv':
        exportToCsv();
        break;
      case 'json':
        exportToJson();
        break;
      case 'txt':
        exportToText();
        break;
    }
  };

  const generateShareableText = () => {
    return [
      `Search Results for: "${query}"`,
      `Found ${results.length} results`,
      '',
      ...results.slice(0, Math.min(5, maxResults)).map((result, index) => 
        `${index + 1}. ${result.title} (${Math.round(result.relevance_score * 100)}% relevance)\n   ${result.content.substring(0, 150)}...`
      ),
      '',
      `Generated by CoWriteAI on ${new Date().toLocaleDateString()}`
    ].join('\n');
  };

  const handleShare = async () => {
    const shareText = generateShareableText();

    switch (shareMethod) {
      case 'copy':
        try {
          await navigator.clipboard.writeText(shareText);
          alert('Results copied to clipboard!');
        } catch (err) {
          console.error('Failed to copy:', err);
        }
        break;
      
      case 'email':
        const emailSubject = encodeURIComponent(`Search Results: "${query}"`);
        const emailBody = encodeURIComponent(shareText);
        window.open(`mailto:?subject=${emailSubject}&body=${emailBody}`);
        break;
      
      case 'link':
        if (navigator.share) {
          try {
            await navigator.share({
              title: `Search Results: "${query}"`,
              text: shareText
            });
          } catch (err) {
            console.error('Share failed:', err);
          }
        } else {
          // Fallback to copy
          await navigator.clipboard.writeText(shareText);
          alert('Results copied to clipboard!');
        }
        break;
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-xl max-w-2xl w-full mx-4 max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-secondary-200">
          <h2 className="text-xl font-semibold text-secondary-900">
            Export Search Results
          </h2>
          <button
            onClick={onClose}
            className="p-2 hover:bg-secondary-100 rounded-lg transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 space-y-6">
          {/* Export Options */}
          <div>
            <h3 className="text-lg font-medium text-secondary-900 mb-4">Export Options</h3>
            
            <div className="space-y-4">
              {/* Format Selection */}
              <div>
                <label className="block text-sm font-medium text-secondary-700 mb-2">
                  Export Format
                </label>
                <div className="grid grid-cols-3 gap-3">
                  {[
                    { value: 'csv', label: 'CSV', icon: FileText, desc: 'Spreadsheet format' },
                    { value: 'json', label: 'JSON', icon: FileText, desc: 'Structured data' },
                    { value: 'txt', label: 'Text', icon: FileText, desc: 'Plain text' }
                  ].map(format => (
                    <button
                      key={format.value}
                      onClick={() => setExportFormat(format.value as any)}
                      className={`
                        p-3 border rounded-lg text-left transition-colors
                        ${exportFormat === format.value
                          ? 'border-primary-500 bg-primary-50 text-primary-700'
                          : 'border-secondary-200 hover:border-secondary-300'
                        }
                      `}
                    >
                      <div className="flex items-center space-x-2 mb-1">
                        <format.icon className="w-4 h-4" />
                        <span className="font-medium">{format.label}</span>
                      </div>
                      <div className="text-xs text-secondary-600">{format.desc}</div>
                    </button>
                  ))}
                </div>
              </div>

              {/* Options */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-2">
                    Max Results
                  </label>
                  <select
                    value={maxResults}
                    onChange={(e) => setMaxResults(Number(e.target.value))}
                    className="w-full px-3 py-2 border border-secondary-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                  >
                    <option value={10}>10 results</option>
                    <option value={25}>25 results</option>
                    <option value={50}>50 results</option>
                    <option value={results.length}>All results ({results.length})</option>
                  </select>
                </div>

                <div className="flex items-center">
                  <label className="flex items-center space-x-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={includeMetadata}
                      onChange={(e) => setIncludeMetadata(e.target.checked)}
                      className="rounded border-secondary-300 text-primary-600 focus:ring-primary-500"
                    />
                    <span className="text-sm font-medium text-secondary-700">
                      Include metadata
                    </span>
                  </label>
                </div>
              </div>
            </div>
          </div>

          {/* Share Options */}
          <div>
            <h3 className="text-lg font-medium text-secondary-900 mb-4">Share Results</h3>
            
            <div className="grid grid-cols-3 gap-3 mb-4">
              {[
                { value: 'copy', label: 'Copy', icon: Copy, desc: 'Copy to clipboard' },
                { value: 'email', label: 'Email', icon: Mail, desc: 'Send via email' },
                { value: 'link', label: 'Share', icon: Link, desc: 'Native sharing' }
              ].map(method => (
                <button
                  key={method.value}
                  onClick={() => setShareMethod(method.value as any)}
                  className={`
                    p-3 border rounded-lg text-left transition-colors
                    ${shareMethod === method.value
                      ? 'border-primary-500 bg-primary-50 text-primary-700'
                      : 'border-secondary-200 hover:border-secondary-300'
                    }
                  `}
                >
                  <div className="flex items-center space-x-2 mb-1">
                    <method.icon className="w-4 h-4" />
                    <span className="font-medium">{method.label}</span>
                  </div>
                  <div className="text-xs text-secondary-600">{method.desc}</div>
                </button>
              ))}
            </div>
          </div>

          {/* Preview */}
          <div>
            <h3 className="text-lg font-medium text-secondary-900 mb-4">Preview</h3>
            <div className="bg-secondary-50 rounded-lg p-4 text-sm text-secondary-700">
              <div className="font-medium mb-2">Query: "{query}"</div>
              <div>Exporting {maxResults} of {results.length} results</div>
              <div>Format: {exportFormat.toUpperCase()}</div>
              <div>Metadata: {includeMetadata ? 'Included' : 'Excluded'}</div>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="flex items-center justify-end space-x-3 p-6 border-t border-secondary-200">
          <button
            onClick={onClose}
            className="px-4 py-2 text-secondary-700 hover:text-secondary-900 transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleShare}
            className="flex items-center space-x-2 px-4 py-2 bg-secondary-600 text-white rounded-lg hover:bg-secondary-700 transition-colors"
          >
            <Share2 className="w-4 h-4" />
            <span>Share</span>
          </button>
          <button
            onClick={handleExport}
            className="flex items-center space-x-2 px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors"
          >
            <Download className="w-4 h-4" />
            <span>Export</span>
          </button>
        </div>
      </div>
    </div>
  );
}